vehicle/urls.py
from django.contrib import admin
from django.urls import path
from vehicle_managementweb import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("signup/",views.RegistrationView.as_view(),name="register"),
    path("",views.LoginView.as_view(),name="signin"),
    path("home/",views.HomeView.as_view(),name="home"),
    path("vehicle/<int:id>/edit/",views.Edit_vehicledetailsView.as_view(),name="edit-vehicle"),
    path("signout",views.Signoutview.as_view(),name="signout"),
    path("vehicle/<int:id>/remove/",views.VehicleDeleteView.as_view(),name="remove"),
    path("vehicle/add/",views.Addvehicleview.as_view(),name="add-vehicle"),
]

vehicle_managementweb/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

# Create your models here.
class User(AbstractUser):
    User_choices=[
        (1, "Super Admin"),
        (2, "Admin"),
        (3, "User"),
    ]
    role=models.PositiveSmallIntegerField(choices=User_choices,default=3)

class Vehicles(models.Model):
    alphanumeric=RegexValidator(r"^[0-9a-zA-Z_]*$",'Only use alphanumeric characters')

    types=[
        ("Two Wheeler","Two Wheeler"),
        ("Three Wheeler","Three Wheeler"),
        ("Four Wheeler","Four Wheeler")
    ]
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    vehicle_number=models.CharField(max_length=100,validators=[alphanumeric])
    vehicle_type=models.CharField(max_length=100,choices=types,default="two wheeler")
    vehicle_model=models.CharField(max_length=100)
    vehicle_description=models.CharField(max_length=250)

vehicle_managementweb/forms.py
from django import forms
from vehicle_managementweb.models import User,Vehicles
from django.contrib.auth.forms import UserCreationForm




class RegistrationForm(UserCreationForm):
    password1=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control border border-primary ","placeholder":"enter password"}))  
    password2=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control border border-primary","placeholder":"confirm password"}))              
    
    class Meta:
        model=User
        fields=['username','email','role']

        widgets={
            "username":forms.TextInput(attrs={"class":"form-control border border-primary","placeholder":"enter username"}),
            "email":forms.EmailInput(attrs={"class":"form-control border border-primary","placeholder":"enter email"}),
            "role":forms.Select(attrs={"class":"form-select form-control border border-primary"})
        } 
class LoginForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control"}))

    
class VehicleForm(forms.ModelForm):
    class Meta:
        model=Vehicles
        fields=["vehicle_number",'vehicle_type','vehicle_model',"vehicle_description"]
        
        widgets={
            "vehicle_number":forms.TextInput(attrs={"class":"form-control",'pattern':'[A-Za-z0-9]+','title':'Enter Alphanumeric Characters Only A-Z,a-z,0-9 ',"placeholder":"enter vehicle number"}),
            "vehicle_model":forms.TextInput(attrs={"class":"form-control","placeholder":"enter vehicle model"}),
            "vehicle_description":forms.TextInput(attrs={"class":"form-control","placeholder":"enter vehicle description"}),
            "vehicle_type":forms.Select(attrs={"class":"form-select form-control"})
        } 

vehicle_managementweb/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.shortcuts import redirect
from django.views.generic import View,CreateView,FormView,ListView,UpdateView,DeleteView
from vehicle_managementweb.forms import RegistrationForm,LoginForm,VehicleForm
from vehicle_managementweb.models import User,Vehicles
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import user_passes_test
from django.views.decorators.cache import never_cache
from django.urls import reverse_lazy


# Create your views here.
def signin_required(fn):
    def wrapper(request,*args,**kwargs):
        if not request.user.is_authenticated:
            return redirect("signin")
        else:
            return fn(request,*args,**kwargs)    
    return wrapper


def superadmin_required(user):
    return user.is_authenticated and user.role in (1,3)

def admin_or_superadmin_required(user):
    return user.is_authenticated and user.role in (1,2)

decs=[never_cache,signin_required,user_passes_test(admin_or_superadmin_required)]
decs1=[never_cache,signin_required,user_passes_test(superadmin_required)]
decs2=[signin_required,never_cache]


class RegistrationView(CreateView):
    model=User
    form_class=RegistrationForm
    template_name="register.html"
    success_url=reverse_lazy("signin")

class LoginView(FormView):
    form_class=LoginForm
    template_name="login.html"

    def post(self,request,*args,**kwargs):
        form=LoginForm(request.POST)
        if form.is_valid():
            uname=form.cleaned_data.get("username")
            pwd=form.cleaned_data.get("password")
            usr=authenticate(request,username=uname,password=pwd)
            if usr:
                login(request,usr)
                return redirect("home")
            else:
                return render(request,"login.html",{"form":form})

@method_decorator(decs2,name="dispatch")
class HomeView(CreateView,ListView):
    model=Vehicles
    form_class=VehicleForm
    template_name='home.html'
    context_object_name="vehicle"
    success_url=reverse_lazy("home")

    def form_valid(self,form):
        form.instance.user=self.request.user
        return super().form_valid(form)
    
@method_decorator(decs2,name="dispatch")
class Addvehicleview(CreateView):
    model=Vehicles
    form_class=VehicleForm
    template_name="add-vehicledetails.html"
    success_url=reverse_lazy("home")
    
@method_decorator(decs,name="dispatch")
class Edit_vehicledetailsView(UpdateView):
    model=Vehicles
    form_class=VehicleForm
    template_name="vehicledetails-edit.html"
    success_url=reverse_lazy("home")
    pk_url_kwarg="id"


@method_decorator(decs1,name="dispatch")
class VehicleDeleteView(View):
    def get(self,request,*args,**kwargs):
        id=kwargs.get("id")
        Vehicles.objects.filter(id=id).delete()
        return redirect("home")
    
    
@method_decorator(decs2,name="dispatch")
class Signoutview(View):
    def get(self,request,*args,**kwargs):
        logout(request)
        return redirect("signin")
    

vehicle_managementweb/templates/add-vehicledetails.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8 mt-5 shadow p-5">
                <form action="" method="post">
                    <h1 class="text-center">Add Vehicle Details</h1>
                    {%csrf_token%}
                    {{form.as_p}}
                    <button type="submit" class="form-control btn btn-outline-success">Add Details</button>
                </form>
            </div>
            <div class="col-2"></div>
        </div>
    </div>
    
</body>
</html>

vehicle_managementweb/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vehicle Management System</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active btn btn-info" aria-current="page" href="{%url 'home'%}" >Home</a>
              </li>
            </ul>
            
          </div>
          <div>
            <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link active btn btn-danger" aria-current="page" href="{%url 'signout'%}" >Logout</a>
                </li>
              </ul>

          </div>
        </div>
      </nav>

    {%block body%}



    {%endblock%}
</body>
</html>

vehicle_managementweb/templates/home.html
{%extends 'base.html'%}
{%block body%}

<div class="container mt-4">
    <h2 class="text-center mb-3">Vehicle Management System</h2>
    {%if request.user.role == 1%}
    <form action="" method="POST" >
        <div class="container">
            <div class="row">
                <div class="col-lg-2"></div>
                <div class="col-lg-8 mb-4">
                    <p class="text-center">
                        <a class="btn btn-warning" type="button" data-bs-toggle="collapse" href="{%url 'add-vehicle'%}"
                            data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                            Add Vehicle Detail
                        </a>    
                    </p>
                    <div class="collapse" id="collapseExample">
                        <div class="card card-body">
                            <div class="mt-4" style="margin-left: 20px;margin-right: 20px;" >
                                {%csrf_token%}
                                {{form.as_p}}
                            </div>
                            <div class="text-center mt-4">
                                <input class="btn btn-info form-control" type="submit" value="Submit">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2"></div>
            </div>
        </div>
    </form>
    {%endif%}
    {%if request.user.role == 3%}
    <br>
    {%endif%}
    </div>
    <div class="container">
        <div class="row mb-5 text-center">
            <div class="col-0"></div>
            <div class="card border border-info col-12">
                <br>
                <table class="table mt-4 mb-4 table table-hover">

                        <tr>           
                            <th>Vehicle Number</th>
                            <th>Vehicle Model</th>
                            <th>Vehicle Type</th>
                            <th>Vehicle Description</th>
                            {%if request.user.role == 1 or request.user.role == 2 %}
                            <th>Actions</th>
                            {%endif%}
                        </tr>  
                        
                {%for i in vehicle%}
                
                    <tr>         
                        <td>{{i.vehicle_number}}</td>
                        <td>{{i.vehicle_model}}</td>
                        <td>{{i.vehicle_type}}</td>
                        <td>{{i.vehicle_description}}</td>
                        <td>
                            {%if request.user.role == 1 or request.user.role == 2 %}
                            <a class="btn btn-sm btn-success mt-2"  href="{%url 'edit-vehicle' i.id%}">Edit</a>
                            {%endif%}
                            {%if request.user.role == 1%}
                            <a class="btn btn-sm btn-danger mt-2" href="{%url 'remove' i.id%}">Delete</a>
                            {%endif%}
                        </td>
                    </tr>
                {%endfor%}
            </table>
            <br>
            </div>
            <div class="col-0"></div>
        </div>
</div>

    
{%endblock%}

vehicle_managementweb/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
  <form action="" method="post">
    {%csrf_token%}
    <section class="vh-100 gradient-custom">
      <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card bg-dark text-white" style="border-radius: 1rem;">
              <div class="card-body p-5 text-center">
    
                <div class="mb-md-5 mt-md-4 pb-5">
    
                  <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                  <p class="text-white-50 mb-5">Please enter your login and password!</p>
                  <div class="form-outline form-white mb-4">
                        <label for="id_username">Username:</label>
                        <input type="text" name="username" class="form-control" required="" id="id_username" placeholder="username">
                        
                        

                  </div>
    
                  <div class="form-outline form-white mb-4">
                        <label for="id_password">Password:</label>
                        <input type="password" name="password" class="form-control" required="" id="id_password" placeholder="password">
                        
                        
                          
                        
                      

                  </div>
    
                  <p class="small mb-5 pb-lg-2"><a class="text-white-50" href="#!">Forgot password?</a></p>
    
                  <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
    
                  <div class="d-flex justify-content-center text-center mt-4 pt-1">
                    <a href="#!" class="text-white"><i class="fa fa-facebook-f fa-lg"></i></a>
                    <a href="#!" class="text-white"><i class="fa fa-twitter fa-lg mx-4 px-2"></i></a>
                    <a href="#!" class="text-white"><i class="fa fa-google fa-lg"></i></a>
                  </div>
    
                </div>
    
                <div>
                  <p class="mb-0">Don't have an account? <a href="{%url 'register'%}" class="text-white-50 fw-bold">Sign Up</a>
                  </p>
                </div>
    
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </form>
</body>
</html>

vehicle_managementweb/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
  <form action="" method="post">
    {%csrf_token%}
    <section class="vh-100 gradient-custom">
      <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card bg-dark text-white" style="border-radius: 1rem;">
              <div class="card-body p-5 text-center">
    
                <div class="mb-md-5 mt-md-4 pb-5">
    
                  <h2 class="fw-bold mb-2 text-uppercase">Register Here!</h2>
                  <p class="text-white-50 mb-5">Please enter your details</p>
                  <div class="form-outline form-white mb-4">
                        <label for="id_username">Username:</label>
                        <input type="text" name="username" class="form-control" required="" id="id_username" placeholder="username">
                        
                        

                  </div>
    
                  <div class="form-outline form-white mb-4">
                        <label for="id_password">email</label>
                        <input type="email" name="email" class="form-control" required="" id="id_email" placeholder="enter email">
                    </div>
                    <div class="form-outline form-white mb-4">
                    <div class="form-outline form-white mb-4">
                        <label for="id_role">Role:</label>
                        <select name="role" class="form-select form-control border border-primary" id="id_role">
                        <option value="1">Super Admin</option>
                    
                        <option value="2">Admin</option>
                    
                        <option value="3" selected="">User</option>
                    
                    </select>
                        
                        
                    </div>

                    </div>
                    <div class="form-outline form-white mb-4">
                        <label for="id_password">Password:</label>
                        <input type="password" name="password1" class="form-control" required="" id="id_password1" placeholder="enter password">
                    </div>
                    <div class="form-outline form-white mb-4">
                        <label for="id_password">Password:</label>
                        <input type="password" name="password2" class="form-control" required="" id="id_password2" placeholder="enter password">
                    </div>

    
    
                  <button class="btn btn-outline-light btn-lg px-5" type="submit">Register</button>

                  <div>
                    <p class="mb-0 mt-3">Already have an account? <a href="{%url 'signin'%}" class="text-white-50 fw-bold">Login</a>
                    </p>
                  </div>
    
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </form>
</body>
</html>

vehicle_managementweb/templates/vehicledetails-edit.html
{%extends 'base.html'%}
{%block body%}

    <div class="container mt-3">
        
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="card">
                    <div class="card-body">
                        <h3 style="text-decoration: none;" class="text-center mt-3 mb-4">Edit Vehicle Details Here</h3>
                        <form action="" method="POST">
                            {%csrf_token%}
                            {{form.as_p}}
                            <div class="text-center">
                                <input class="btn btn-primary btn-sm mt-2 mb-3 form-control" type="submit" value="Submit">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-2"></div>
        </div>
    </div>

{%endblock%}